name: Node.js Package
on:
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: set package version
        run: npm version --allow-same-version --no-git-tag-version ${{ steps.get_version.outputs.version-without-v }}
      - name: Install Dependencies
        run: |
          npm install
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
